### ISSUE TITLE
[meta] extract `containerFactory`

### ISSUE THREAD

**Issue by giogonzo** [buildo/webseed#21]
← #18
## requirements

probably:
- [x] its own repo `buildo/react-container`
- [x] start from modified version available in step0 of tutorial
- [x] update book: Components taxonomy
- [x] update step0 boilerplate (just rebase it probably)
- [x] double check current way of determining if `@queries` or `@commands` are required
  - ~~it could be that we are wrapping in a useless hoc (empty query or empty commands declaration)~~
## specs

{optional: describe technical specs to implement this feature, if not obvious}
## misc

{optional: other useful info}

**Comment by giogonzo** [comment]
@buildo/frontend suggestions / requests?

**Comment by FrancescoCioria** [comment]
why it's own repo? doesn't `react-container` require `avenger`?

**Comment by giogonzo** [comment]
> why it's own repo? doesn't react-container require avenger?

basically it requires everything: `state`, `avenger`, `revenge`, ?

**Comment by FrancescoCioria** [comment]
I agree with extracting stable and general components/logic to external libraries, but (I think) increasing the number of repos will also increase the work we have to do to maintain them.

Of course also putting it inside a "big" repo like `avenger`/`revenge` would also be a problem as they would be linked to a precise version of their bigger brother...

What about creating a single repo to group all these `avenger` nicety/utils/add-ons/decorators?

As I already said, I'm proposing this to avoid the overhead increase due to a big number of internal repos/dependencies

**Comment by gabro** [comment]
buildo/stuff?

**Comment by gabro** [comment]
buildo/all-the-stuff?

**Comment by ascariandrea** [comment]
I agree with @FrancescoCioria, a dedicated repo seems much overhead in terms of maintenance.
I don't have the all picture to give you a measured feedback, but aren't we updating `revenge` too? This can be the cause of a probable refactor of this component in the future.
Let's reduce isolation for now.

**Comment by giogonzo** [comment]
> What about creating a single repo to group all these avenger nicety/utils/add-ons/decorators?

Yes this is probably the preferred long term solution, but the quick-and-decent-enough for now would be:
- split (just 1 or 2 more repos, I promise!)
  - maybe no npm packages, not just yet (github only)
- provide a single boilerplate file for projects, re-exporting all

**Comment by giogonzo** [comment]
api-wise, I propose two small changes:
- rename `containerFactory` to `container` (default export anyway, not super interesting)
- and
  instead of

``` js
const ComponentContainer = container(Component, { ...config });
export default ComponentContainer(Props => Props);
```

simplify to either:

``` js
export default container(Component, { ...config }, Props => Props)
```

or

``` js
export default container(Component, {
  ...config, // all of this is optional...
  mapProps: Props => Props // this is optional too, although very often used
})
```

Thoughts? especially @francescogior

**Comment by francescogior** [comment]
Same for me.

If I remember well, I had tried to make it as curried function so the first one should be as it is now (not sure if it works though)
Second one probably is more concise

**Comment by gabro** [comment]
How about having

``` js
container(Component, { ...config })(Props => Props)
```

and

``` js
container(Component, { ...config }, Props => Props)
```

both acceptable? It reminds me of a famous interview question? :P

**Comment by giogonzo** [comment]
yup, as @francescogior says, that's probably already the case :P

I vote for the second option though, as both `config` and `mapProps` are theoretically optional

**Comment by giogonzo** [comment]
(and of course you can't have an optional `config` in this way instead)

**Comment by giogonzo** [comment]
here it is: https://github.com/buildo/react-container

**Comment by ascariandrea** [comment]
Remember to define deps :)

**Comment by giogonzo** [comment]
added deps, fixed bugs, updated book here: https://buildo.gitbooks.io/book/content/frontend/guidelines/2.components.html
